# environment

environment:
  nodejs_version: "5"

  TEST_PORT: 3003
  NODE_ENV: test
  DEBUG: false

  # coverage

  COVERALLS_GIT_BRANCH: '$(APPVEYOR_REPO_BRANCH)'
  COVERALLS_REPO_TOKEN:
    secure: SMqGG7P6M0nuAs0gQvjnZHKPU1xruMPd5apdbf0n26efaJmP/x8h8YLzsRB/w+sk

# general

version: 1.0.{build}

skip_tags: true
cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json

platform:
  - x64

# build

build: off

install:
  - cmd: npm install
  - cmd: npm install -g gulp

on_success:
  - cmd: gulp coveralls

# tests

test_script:
  - cmd: gulp tests
